### PR TITLE
feat(global): fix split architectural indices

### LINKED ISSUE #5: Separate platforms index
We already have enough platform specific code to separate the index per platform.

### PR DESCRIPTION
**Pull request by fjcaetano**
fix #5

### CODE REVIEW

File: index.js.android.js [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+const convertWorkoutDates = (input) => ({
+  calories: input.calories,
+  endDate: new Date(input.endDate),
+  metadata: input.metadata,
+  startDate: new Date(input.startDate),
+});
+
+export default {
+  openAppleHealth: () => {
+    RNHealthKit.openAppleHealth();
```
Comment (cabelitos) [inline index.js.android.js]: I think this should be a NOOP

File: index.js.android.js [hunk 2]
```diff
@@ -0,0 +1,52 @@
+import { NativeModules, PushNotificationIOS, Platform } from 'react-native';
+
+const { RNHealthKit } = NativeModules;
+
+const convertWorkoutDates = (input) => ({
```
Comment (cabelitos) [inline index.js.android.js]: we don't need this

File: index.js.android.js [hunk 3]
```diff
@@ -0,0 +1,52 @@
+import { NativeModules, PushNotificationIOS, Platform } from 'react-native';
+
+const { RNHealthKit } = NativeModules;
```
Comment (cabelitos) [inline index.js.android.js]: we dont need this

File: index.js.android.js [hunk 4]
```diff
@@ -0,0 +1,52 @@
+import { NativeModules, PushNotificationIOS, Platform } from 'react-native';
```
Comment (cabelitos) [inline index.js.android.js]: we dont need this
